name: EcorteWhitelist
version: '1.1'
main: org.ecorte.ecorteWhitelist.EcorteWhitelist
api-version: '1.21'
authors: [ Ecorte ]
description: A MariaDb based whitelist plugin for Minecraft servers.
dependencies:
  server:
    CommandAPI:
      load: BEFORE
      required: true
      join-classpath: true
    LuckPerms:
      load: BEFORE
      required: true
      join-classpath: true